### ISSUE TITLE
你好，请问是否支持 element 组件库

### ISSUE THREAD

**Issue by langzhou** [yeqisong/crx3-dev-template#1]
你好，请问是否支持 element 组件库？

**Comment by yeqisong** [comment]
template是模板，你到主页看cli项目，element只是ui框架，建立项目后，直接添加各类ui框架即可。是支持的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月13日(周二) 下午4:03
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [yeqisong/crx3-dev-template] 你好，请问是否支持 element 组件库 (#1)




 
你好，请问是否支持 element 组件库？

**Comment by langzhou** [comment]
> template是模板，你到主页看cli项目，element只是ui框架，建立项目后，直接添加各类ui框架即可。是支持的。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年7月13日(周二) 下午4:03 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [yeqisong/crx3-dev-template] 你好，请问是否支持 element 组件库 (#1) 你好，请问是否支持 element 组件库？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

好的，我了解下~

**Comment by langzhou** [comment]
你好，通过 npm 安装 element 组件后，然后在 main.js 里引用，build 的时候会报错。不知道是不是我用的方法不对：
<img width="1295" alt="WX20210713-164313@2x" src="https://user-images.githubusercontent.com/6987229/125420930-786be588-250e-487d-8ff0-f04ba1a8ac63.png">

**Comment by langzhou** [comment]
老哥，找到问题所在了，加了代码忽略对 commonjs 文件的处理就可以了：
![image](https://user-images.githubusercontent.com/6987229/125913334-cdbe1d2a-0526-4d5c-b3c0-5319e3ff2d48.png)

**Comment by yeqisong** [comment]
感谢感谢，
更好的做法是在拉取项目后，在你的项目vite配置里处理commonjs



修改了，但是最近确实太忙，所以没去更新。


但是，建议使用antd的按需加载组件，第三发UI组件始终会存在一个问题：很多有风险的函数，无法在chrome拓展中使用，比如用到eval等，
所以，建议用一些简单的UI组件来开发，或者自己写一些UI组件（个人建议）。


之后会考虑好好测试下各个UI组件的支持情况，目前发现就是antd全部引入时，它内部用到了eval、Function等函数，是chrome拓展不支持的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yeqisong/crx3-dev-template"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月16日(星期五) 下午3:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yeqisong/crx3-dev-template] 你好，请问是否支持 element 组件库 (#1)





 
老哥，找到问题所在了，加了代码忽略对 commonjs 文件的处理就可以了：
